# Generated by Django 4.2.1 on 2023-06-05 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Difficultion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Уровень сложности')),
            ],
            options={
                'verbose_name': 'Уровень сложности',
                'verbose_name_plural': 'Уровни сложности',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('time_limit', models.TimeField(verbose_name='Время прохождения')),
                ('quantity_attempts', models.IntegerField(verbose_name='Количество попыток')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='djangotests.category', verbose_name='Категория')),
                ('dif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='djangotests.difficultion', verbose_name='Уровень сложности')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(auto_now_add=True, verbose_name='Начало прохождения теста')),
                ('time', models.TimeField(null=True, verbose_name='Время прохождения')),
                ('result', models.IntegerField(null=True, verbose_name='Результат теста')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangotests.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='djangotests.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='AnswerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(max_length=255, verbose_name='Ответы на тест')),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangotests.question', verbose_name='Вопрос')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answersUser', to='djangotests.session', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователя',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='Вариант ответа')),
                ('right', models.BooleanField(verbose_name='Является правильным ответом')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='djangotests.question', verbose_name='Идентификатор вопроса')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
